import type { Denuncia, Estadisticas, User } from "@/types"

export const mockDenuncias: Denuncia[] = [
  {
    id: "1",
    tipo: "Deforestación",
    titulo: "Tala ilegal masiva en Parque Nacional Natural",
    descripcion:
      "Se observa tala masiva de árboles nativos en zona protegida del Parque Nacional Natural. Aproximadamente 5 hectáreas afectadas. Se escuchan motosierras durante la noche y se observan camiones transportando madera.",
    ubicacion: {
      lat: 4.711,
      lng: -74.0721,
      direccion: "Parque Nacional Natural Chingaza, Cundinamarca",
    },
    evidencias: ["/deforestation-illegal-logging.jpg", "/cut-trees-forest.jpg"],
    denunciante: {
      id: "dem1",
      nombre: "Carlos Pérez",
      email: "carlos.perez@email.com",
      anonimo: false,
    },
    status: "EN_PROCESO",
    fechaCreacion: "2025-01-15T10:30:00Z",
    fechaActualizacion: "2025-01-16T14:20:00Z",
    prioridad: "alta",
    visibilidadPublica: true,
    revisor: {
      id: "rev1",
      nombre: "Dr. Carlos Mendoza",
      organizacion: "Grupo VerdeLex",
      fechaAsignacion: "2025-01-15T15:00:00Z",
    },
    reacciones: {
      likes: 234,
      usuariosLike: ["dem2", "rev2", "rev3"],
    },
    comentarios: [
      {
        id: "c1",
        denunciaId: "1",
        usuarioId: "rev1",
        usuarioNombre: "Dr. Carlos Mendoza",
        usuarioRole: "revisor",
        contenido:
          "He tomado el caso. Estamos recopilando evidencia adicional y contactando a las autoridades ambientales.",
        fechaCreacion: "2025-01-15T16:00:00Z",
      },
      {
        id: "c2",
        denunciaId: "1",
        usuarioId: "dem2",
        usuarioNombre: "María González",
        usuarioRole: "demandante",
        contenido: "Yo también he visto actividad sospechosa en esa zona. Puedo aportar más fotos.",
        fechaCreacion: "2025-01-16T09:00:00Z",
      },
    ],
    vistas: 1523,
    compartidos: 45,
  },
  {
    id: "2",
    tipo: "Contaminación hídrica",
    titulo: "Vertimiento continuo de químicos al Río Bogotá",
    descripcion:
      "Empresa textil ubicada en el sector industrial está vertiendo residuos químicos directamente al Río Bogotá. El agua presenta coloración rojiza y olor fuerte. Peces muertos en la orilla.",
    ubicacion: {
      lat: 4.6097,
      lng: -74.0817,
      direccion: "Río Bogotá, Sector Industrial Soacha",
    },
    evidencias: ["/river-pollution-chemical-waste.jpg", "/dead-fish-contaminated-water.jpg"],
    denunciante: {
      id: "dem2",
      nombre: "María González",
      email: "maria.gonzalez@email.com",
      anonimo: false,
    },
    status: "RECIBIDA",
    fechaCreacion: "2025-01-17T08:15:00Z",
    fechaActualizacion: "2025-01-17T08:15:00Z",
    prioridad: "critica",
    visibilidadPublica: true,
    reacciones: {
      likes: 456,
      usuariosLike: ["dem1", "rev1", "rev2"],
    },
    comentarios: [
      {
        id: "c3",
        denunciaId: "2",
        usuarioId: "rev2",
        usuarioNombre: "Dra. María González",
        usuarioRole: "revisor",
        contenido:
          "Caso muy grave. Voy a tomar esta denuncia. Necesitamos muestras de agua para análisis de laboratorio.",
        fechaCreacion: "2025-01-17T10:30:00Z",
      },
    ],
    vistas: 2341,
    compartidos: 89,
  },
  {
    id: "3",
    tipo: "Minería ilegal",
    titulo: "Operación minera ilegal en zona de reserva forestal",
    descripcion:
      "Extracción ilegal de oro con maquinaria pesada en zona de reserva forestal. Deforestación asociada y contaminación de quebradas con mercurio. Operación activa 24/7.",
    ubicacion: {
      lat: 6.2442,
      lng: -75.5812,
      direccion: "Reserva Forestal, Medellín, Antioquia",
    },
    evidencias: ["/illegal-mining-gold-extraction.jpg", "/mining-machinery-forest.jpg"],
    denunciante: {
      anonimo: true,
    },
    status: "RESUELTA",
    fechaCreacion: "2024-12-20T12:00:00Z",
    fechaActualizacion: "2025-01-10T16:30:00Z",
    prioridad: "alta",
    visibilidadPublica: true,
    revisor: {
      id: "rev2",
      nombre: "Dra. María González",
      organizacion: "Protectores del Río",
      fechaAsignacion: "2024-12-21T09:00:00Z",
    },
    reacciones: {
      likes: 678,
      usuariosLike: ["dem1", "dem2", "rev1", "rev3"],
    },
    comentarios: [
      {
        id: "c4",
        denunciaId: "3",
        usuarioId: "rev2",
        usuarioNombre: "Dra. María González",
        usuarioRole: "revisor",
        contenido:
          "Caso resuelto exitosamente. Las autoridades intervinieron y desmantelaron la operación ilegal. Se están realizando trabajos de restauración.",
        fechaCreacion: "2025-01-10T16:30:00Z",
      },
    ],
    vistas: 3456,
    compartidos: 123,
  },
  {
    id: "4",
    tipo: "Quema de bosques",
    titulo: "Incendio provocado para expansión ganadera",
    descripcion:
      "Quema intencional de bosque nativo para convertir el terreno en pastizales. Se observaron personas iniciando el fuego. Área aproximada de 10 hectáreas.",
    ubicacion: {
      lat: 3.4516,
      lng: -76.532,
      direccion: "Zona Rural, Cali, Valle del Cauca",
    },
    evidencias: ["/forest-fire-burning-trees.jpg"],
    denunciante: {
      id: "dem1",
      nombre: "Carlos Pérez",
      email: "carlos.perez@email.com",
      anonimo: false,
    },
    status: "EN_PROCESO",
    fechaCreacion: "2025-01-14T15:45:00Z",
    fechaActualizacion: "2025-01-15T09:20:00Z",
    prioridad: "critica",
    visibilidadPublica: true,
    revisor: {
      id: "rev3",
      nombre: "Ing. Roberto Silva",
      organizacion: "Universidad Ambiental",
      fechaAsignacion: "2025-01-14T18:00:00Z",
    },
    reacciones: {
      likes: 345,
      usuariosLike: ["dem2", "rev1"],
    },
    comentarios: [
      {
        id: "c5",
        denunciaId: "4",
        usuarioId: "rev3",
        usuarioNombre: "Ing. Roberto Silva",
        usuarioRole: "revisor",
        contenido:
          "Estamos coordinando con bomberos y autoridades ambientales. Se ha iniciado investigación para identificar responsables.",
        fechaCreacion: "2025-01-15T09:20:00Z",
      },
    ],
    vistas: 1876,
    compartidos: 67,
  },
  {
    id: "5",
    tipo: "Contaminación del aire",
    titulo: "Emisiones industriales sin control de filtros",
    descripcion:
      "Fábrica de productos químicos emitiendo humo negro constantemente. No se observan sistemas de filtración. Afecta a comunidades cercanas con problemas respiratorios.",
    ubicacion: {
      lat: 7.0698,
      lng: -73.1078,
      direccion: "Zona Industrial, Bucaramanga, Santander",
    },
    evidencias: ["/factory-smoke-air-pollution.jpg"],
    denunciante: {
      anonimo: true,
    },
    status: "RECIBIDA",
    fechaCreacion: "2025-01-16T11:30:00Z",
    fechaActualizacion: "2025-01-16T11:30:00Z",
    prioridad: "media",
    visibilidadPublica: true,
    reacciones: {
      likes: 189,
      usuariosLike: ["dem1"],
    },
    comentarios: [],
    vistas: 945,
    compartidos: 23,
  },
  {
    id: "6",
    tipo: "Tráfico de fauna",
    titulo: "Venta ilegal de especies protegidas en mercado",
    descripcion:
      "Se observa venta de loros, guacamayas y tortugas en mercado local. Especies en condiciones deplorables. Vendedores operan abiertamente.",
    ubicacion: {
      lat: 10.9639,
      lng: -74.7964,
      direccion: "Mercado Central, Barranquilla, Atlántico",
    },
    evidencias: ["/illegal-wildlife-trade-parrots.jpg"],
    denunciante: {
      id: "dem2",
      nombre: "María González",
      email: "maria.gonzalez@email.com",
      anonimo: false,
    },
    status: "EN_PROCESO",
    fechaCreacion: "2025-01-13T14:20:00Z",
    fechaActualizacion: "2025-01-14T10:15:00Z",
    prioridad: "alta",
    visibilidadPublica: true,
    revisor: {
      id: "rev1",
      nombre: "Dr. Carlos Mendoza",
      organizacion: "Grupo VerdeLex",
      fechaAsignacion: "2025-01-13T16:00:00Z",
    },
    reacciones: {
      likes: 512,
      usuariosLike: ["dem1", "rev2", "rev3"],
    },
    comentarios: [
      {
        id: "c6",
        denunciaId: "6",
        usuarioId: "rev1",
        usuarioNombre: "Dr. Carlos Mendoza",
        usuarioRole: "revisor",
        contenido: "Coordinando operativo con policía ambiental. Necesitamos más evidencia fotográfica si es posible.",
        fechaCreacion: "2025-01-14T10:15:00Z",
      },
    ],
    vistas: 2103,
    compartidos: 78,
  },
  {
    id: "7",
    tipo: "Vertimiento de residuos",
    titulo: "Botadero ilegal de residuos peligrosos",
    descripcion:
      "Lote baldío utilizado como botadero de residuos industriales y hospitalarios. Presencia de jeringas, químicos y materiales tóxicos. Riesgo para comunidad cercana.",
    ubicacion: {
      lat: 4.142,
      lng: -73.6266,
      direccion: "Periferia, Villavicencio, Meta",
    },
    evidencias: ["/illegal-dump-hazardous-waste.jpg"],
    denunciante: {
      anonimo: true,
    },
    status: "RECIBIDA",
    fechaCreacion: "2025-01-17T16:45:00Z",
    fechaActualizacion: "2025-01-17T16:45:00Z",
    prioridad: "alta",
    visibilidadPublica: true,
    reacciones: {
      likes: 267,
      usuariosLike: ["dem1", "dem2"],
    },
    comentarios: [],
    vistas: 834,
    compartidos: 34,
  },
  {
    id: "8",
    tipo: "Contaminación hídrica",
    titulo: "Derrame de petróleo en quebrada",
    descripcion:
      "Derrame de crudo desde oleoducto afectando quebrada y fuentes de agua de comunidades indígenas. Fauna acuática muerta. Urgente intervención.",
    ubicacion: {
      lat: 5.0689,
      lng: -75.5174,
      direccion: "Zona Rural, Arauca, Arauca",
    },
    evidencias: ["/oil-spill-river-contamination.jpg"],
    denunciante: {
      id: "dem1",
      nombre: "Carlos Pérez",
      email: "carlos.perez@email.com",
      anonimo: false,
    },
    status: "EN_PROCESO",
    fechaCreacion: "2025-01-12T07:30:00Z",
    fechaActualizacion: "2025-01-13T11:45:00Z",
    prioridad: "critica",
    visibilidadPublica: true,
    revisor: {
      id: "rev2",
      nombre: "Dra. María González",
      organizacion: "Protectores del Río",
      fechaAsignacion: "2025-01-12T09:00:00Z",
    },
    reacciones: {
      likes: 892,
      usuariosLike: ["dem2", "rev1", "rev3"],
    },
    comentarios: [
      {
        id: "c7",
        denunciaId: "8",
        usuarioId: "rev2",
        usuarioNombre: "Dra. María González",
        usuarioRole: "revisor",
        contenido:
          "Caso de máxima prioridad. Hemos alertado a autoridades nacionales y organismos internacionales. Equipo en terreno evaluando daños.",
        fechaCreacion: "2025-01-13T11:45:00Z",
      },
    ],
    vistas: 4521,
    compartidos: 156,
  },
]

export const mockEstadisticas: Estadisticas = {
  totalDenuncias: 1247,
  denunciasMes: 89,
  denunciasResueltas: 456,
  denunciasEnProceso: 312,
  usuariosActivos: 3420,
  porcentajeAcompañamiento: 68,
}

export const contactosUtiles = [
  {
    nombre: "Grupo VerdeLex",
    tipo: "Asesoría legal",
    email: "info@verdelex.org",
    telefono: "+57 1 234 5678",
    descripcion: "Apoyo legal especializado en derecho ambiental",
  },
  {
    nombre: "Protectores del Río",
    tipo: "ONG contaminación hídrica",
    email: "contacto@protectoresrio.org",
    telefono: "+57 1 345 6789",
    descripcion: "Especialistas en protección de recursos hídricos",
  },
  {
    nombre: "Universidad Ambiental",
    tipo: "Soporte técnico",
    email: "soporte@uniambiental.edu",
    telefono: "+57 1 456 7890",
    descripcion: "Análisis técnico y estudios de impacto ambiental",
  },
  {
    nombre: "Defensoría del Ambiente",
    tipo: "Mediación y seguimiento",
    email: "defensoria@ambiente.gov.co",
    telefono: "+57 1 567 8901",
    descripcion: "Mediación entre ciudadanos y autoridades ambientales",
  },
]

export const mockUsers: User[] = [
  {
    id: "admin1",
    nombre: "Ana Rodríguez",
    email: "admin@gmail.com", // Email actualizado según requerimiento
    role: "admin",
    organizacion: "Justicia Verde",
    denunciasCreadas: 0,
    denunciasResueltas: 0,
    fechaRegistro: "2024-01-01T00:00:00Z",
    activo: true,
    avatar: "/admin-woman.png",
  },
  {
    id: "dem1",
    nombre: "Carlos Pérez",
    email: "demandante@gmail.com", // Email actualizado según requerimiento
    role: "demandante",
    denunciasCreadas: 5,
    fechaRegistro: "2024-06-15T00:00:00Z",
    activo: true,
    avatar: "/thoughtful-man-city.png",
  },
  {
    id: "dem2",
    nombre: "María González",
    email: "maria.gonzalez@email.com",
    role: "demandante",
    denunciasCreadas: 3,
    fechaRegistro: "2024-08-20T00:00:00Z",
    activo: true,
    avatar: "/diverse-woman-citizen.png",
  },
  {
    id: "rev1",
    nombre: "Dr. Carlos Mendoza",
    email: "visualizador@gmail.com", // Email actualizado según requerimiento (revisor = visualizador)
    role: "revisor",
    organizacion: "Grupo VerdeLex",
    especialidad: "Derecho Ambiental",
    telefono: "+57 1 234 5678",
    denunciasEnRevision: 8,
    denunciasResueltas: 45,
    fechaRegistro: "2024-02-10T00:00:00Z",
    activo: true,
    avatar: "/lawyer-man.jpg",
  },
  {
    id: "rev2",
    nombre: "Dra. María González",
    email: "mgonzalez@protectoresrio.org",
    role: "revisor",
    organizacion: "Protectores del Río",
    especialidad: "Contaminación Hídrica",
    telefono: "+57 1 345 6789",
    denunciasEnRevision: 5,
    denunciasResueltas: 32,
    fechaRegistro: "2024-03-05T00:00:00Z",
    activo: true,
    avatar: "/lawyer-woman.jpg",
  },
  {
    id: "rev3",
    nombre: "Ing. Roberto Silva",
    email: "rsilva@uniambiental.edu",
    role: "revisor",
    organizacion: "Universidad Ambiental",
    especialidad: "Análisis Técnico Ambiental",
    telefono: "+57 1 456 7890",
    denunciasEnRevision: 6,
    denunciasResueltas: 28,
    fechaRegistro: "2024-04-12T00:00:00Z",
    activo: true,
    avatar: "/engineer-man.png",
  },
]
